---
- name: Install certbot with the apache plugin
  apt: 
    upgrade: safe
    update_cache: yes
    cache_valid_time: 3600  

- name: Install Repository (DEB)
  apt:
    name: software-properties-common
    state: latest

- name: Update all packages to the latest version
  apt:
    upgrade: yes

- name: Install certbot-apache (DEB)
  apt:
    name: python3-certbot-apache
    state: latest

- name: Copy Laravelapp-le-ssl.conf
  copy:
    src: tasks/laravelapp-le-ssl.conf
    dest: /etc/apache2/sites-enabled/laravelapp-le-ssl.conf

- name: Restart Apache2
  service:
    name: apache2
    state: restarted
  become: yes