---
- name: Install certbot with the apache plugin
  apt: 
    upgrade: yes
    update_cache: yes
    cache_valid_time: 3600  

- name: Install Repository (DEB)
  apt:
    name: software-properties-common
    state: latest

# - name: Enable Certbot Repository (DEB)
#   command: add-apt-repository ppa:certbot/certbot

- name: Update all packages to the latest version
  apt:
    upgrade: yes

- name: Install certbot-apache (DEB)
  apt:
    name: python3-certbot-apache
    state: latest

- name: Restart Apache2
    service:
      name: apache2
      state: restarted
    become: yes