---
- name: Install SSL Certificate
  hosts: webservers
  remote_user: root  

  vars: 

    certbot_generate_certificates: true
    certbot_register_email: philip.i.nwachukwu@gmail.com
    certbot_certificate_domains:
        - phil-altschool.me

  roles:
        - { role: certbot-apache, become: yes }