---

- name: Setup webserver
  hosts: webservers

  tasks:
 
  - name: Run apt upgrade
    apt:
      upgrade: "yes"
      update_cache: yes
      cache_valid_time: 432000

  - name: Add php sury repository from PPA and install its signing key on Debian target
    script: scripts/php_8.1_repo.sh
  
  - name: Install php rerequisites
    ansible.builtin.apt:
      pkg:
      - ca-certificates
      - apt-transport-https
      - software-properties-common
      - lsb-release
      - gnupg2
      - curl
 
  - name: Install php8.1
    apt:
      name: php8.1
      update_cache: yes
      state: latest
    tags:
    - php8.1
  
  - name: Install Apache2
    become: true
    apt:
      name: apache2
      state: latest
  
  - name: Install PostgreSQL DB Server
    script: scripts/postgresql.sh

  - name: Install a list of packages
    ansible.builtin.apt:
      pkg:
      - php8.1-opcache 
      - php8.1-soap 
      - php8.1-zip 
      - php8.1-intl 
      - php8.1-mysql 
      - php8.1-common  
      - php8.1-xmlrpc 
      - php8.1-curl 
      - php8.1-gd 
      - php8.1-imagick 
      - php8.1-dev 
      - php8.1-imap 
      - php8.1-cli
      - php8.1-xml
      - php8.1-pgsql
      - php8.1-fpm
      - libapache2-mod-php8.1
      - git
      - zip
      - unzip
      state: latest
      update_cache: yes
 
  - name: Install UFW
    ansible.builtin.apt:
      name: ufw  
 
  - name: Allow SSH,
    ufw:
      rule: allow
      name: OpenSSH

  - name: Apache,
    ufw:
      rule: allow
      port:  "80"
  
  - name: Apache Secure,
    ufw:
      rule: allow
      port:  "443"
  
  - name: UFW Enable,
    ufw:
      state: disabled
  
  - name: download composer
    script: scripts/install_composer.sh
  
  - name: Move composer globally
    become: true
    command: mv composer.phar /usr/local/bin/composer
 
  - name: Set permissions on composer
    become: true
    file:
      path: /usr/local/bin/composer
      mode: "a+x"

  - name: Clone laravel codebase
    git:
      repo: https://github.com/f1amy/laravel-realworld-example-app.git
      dest: /var/www/laravelapp
    register: repo_clone
    failed_when:
    - repo_clone.failed
    - not 'Local modifications exist in repository' in repo_clone.msg
  
  - name: "Uncomment the line"
    replace:
      path: /var/www/laravelapp/routes/web.php
      regexp: "/*Route"
      replace: "Route"
 
  - name: take ownership of laravel folder
    file:
      path: www-data:www-data /var/www/laravelapp
      state: directory
      recurse: yes
      owner: "{{ ansible_effective_user_id }}"
      group: "{{ ansible_effective_group_id }}"
    
  - name: set permissions for Laravel folder
    file:
      path: /var/www/laravelapp
      state: directory
      recurse: yes
      mode: '775'

  - name: Download and installs all libs and dependencies
    composer:
      command: install
      working_dir: /var/www/laravelapp
    environment:
      COMPOSER_ALLOW_SUPERUSER: "1"

  - name: copy env file
    copy:
      src: /var/www/laravelapp/.env.example
      remote_src: yes
      dest: /var/www/laravelapp/.env
      owner: "{{ ansible_effective_user_id }}"
      group: "{{ ansible_effective_group_id }}"
      mode: '0644'
    become: yes

  - name: copy apache config
    copy:
        src: stubs/laravelapp.conf
        dest: /etc/apache2/sites-available/laravelapp.conf
        owner: "{{ ansible_effective_user_id }}"
        group: "{{ ansible_effective_group_id }}"
        mode: '0644'
    become: yes

  - name: set server name
    replace:
        path: /etc/apache2/sites-available/laravelapp.conf
        regexp: '$SERVER_NAME'
        replace: '{{ ansible_host }}'
    become: yes

  - name: enable the new config
    shell: |
      a2ensite laravelapp.conf
      a2dissite 000-default.conf
      a2enmod rewrite
      service apache2 restart
    become: yes

  - name: setup laravel
    shell: |
        cd /var/www/laravelapp
        php artisan key:generate
    become: yes
      
