---

- name: Setup webserver
  hosts: webservers

  tasks:
 
  - name: Add php sury repository from PPA and install its signing key on Debian>
    script: scripts/php_8.1_repo.sh

  - name: Add postresql repo
    script: scripts/postgresql_repo.sh

  - name: Run apt update and upgrade
    apt:
      update_cache: yes
      upgrade: safe
   
  - name: Install php rerequisites
    ansible.builtin.apt:
      pkg:
      - ca-certificates
      - apt-transport-https
      - software-properties-common
      - lsb-release
      - gnupg2
      - curl
 
  - name: Install php8.1
    apt:
      name: php8.1
      state: latest
      update_cache: yes
    tags:
    - php8.1
  
  - name: Install Apache2
    become: true
    apt:
      name: apache2
      state: latest
      update_cache: yes
  
  - name: Install PostgreSQL DB Server
    script: scripts/postgresql.sh

  - name: Install a list of packages
    ansible.builtin.apt:
      pkg:
      - php8.1-opcache 
      - php8.1-soap 
      - php8.1-zip 
      - php8.1-intl 
      - php8.1-mysql 
      - php8.1-common  
      - php8.1-xmlrpc 
      - php8.1-curl 
      - php8.1-gd 
      - php8.1-imagick 
      - php8.1-dev 
      - php8.1-imap 
      - php8.1-cli
      - php8.1-xml
      - php8.1-pgsql
      - php8.1-fpm
      - libapache2-mod-php8.1
      - git
      - zip
      - unzip
      state: latest
      update_cache: yes
 
  - name: Install UFW
    ansible.builtin.apt:
      name: ufw  
 
  - name: Allow SSH,
    ufw:
      rule: allow
      name: OpenSSH

  - name: Apache,
    ufw:
      rule: allow
      port:  "80"
  
  - name: Apache Secure,
    ufw:
      rule: allow
      port:  "443"

  - name: Open DBport,
    ufw:
      rule: allow
      port:  "5432"
  
  - name: UFW Enable,
    ufw:
      state: enabled
  
  - name: download composer
    script: scripts/install_composer.sh
  
  - name: Move composer globally
    become: true
    command: mv composer.phar /usr/local/bin/composer
 
  - name: Set permissions on composer
    become: true
    file:
      path: /usr/local/bin/composer
      mode: a+x

  - name: Clone laravel codebase
    git:
      repo: https://github.com/f1amy/laravel-realworld-example-app.git
      dest: /var/www/laravelapp
    register: repo_clone
    failed_when:
    - repo_clone.failed
    - not 'Local modifications exist in repository' in repo_clone.msg
  
  - name: Template a web.php to /routes/web.php
    command: echo mytemplates/web.php > /var/www/laravelapp/routes/web.php

  - name: Download and installs all libs and dependencies
    composer:
      command: update
      working_dir: /var/www/laravelapp
    environment:
      COMPOSER_ALLOW_SUPERUSER: "1"  
  
  - name: copy .env
    copy:
        src: mytemplates/.env
        dest: /var/www/laravelapp/.env
        owner: www-data
        group: www-data
        mode: '775'
    become: yes   

  - name: copy .htaccess
    copy:
        src: stubs/.htaccess
        dest: /var/www/laravelapp/.htaccess
        owner: www-data
        group: www-data
        mode: '775'
    become: yes

  - name: copy apache config
    copy:
        src: stubs/laravelapp.conf
        dest: /etc/apache2/sites-available/laravelapp.conf
        owner: www-data
        group: www-data
        mode: '775'
    become: yes
  
  - name: enable the new config
    shell: |
      a2ensite laravelapp.conf
      a2dissite 000-default.conf
      a2enmod rewrite
    become: yes

  - name: Generate App Key
    shell: |
        cd /var/www/laravelapp
        php artisan key:generate
    become: yes
  
  - name: Set artisan config
    shell: |
        cd /var/www/laravelapp
        php artisan config:cache
    become: yes

#  - name: Migrate 
#    shell: |
#        cd /var/www/laravelapp
#        php artisan migrate --seed
#    become: yes   
   
  - name: Change ownership and set permissions of laravel folder
    file:
      path: /var/www/laravelapp/
      recurse: yes
      owner: www-data
      group: www-data
      mode: '775'
    become: yes

  - name: Change group and set permissions of storage folder
    file:
      path: /var/www/laravelapp/storage/
      recurse: yes
      group: www-data
      mode: u=rwx,g=rwx,o=rwx
    become: yes

  - name: Change group and set permissions of cache
    file:
      path: /var/www/laravelapp/bootstrap/cache/
      recurse: yes
      group: www-data
      mode: u=rwx,g=rwx,o=rx
    become: yes
  
  - name: Change group and set permissions for laravel.logs
    file:
      path: /var/www/laravelapp/storage/logs/laravel.log
      group: www-data
      state: file
      mode: u=rwx,g=rwx,o=w
    become: yes  
 
  - name: Restart Apache2
    service:
      name: apache2 
      state: restarted
    become: yes
 
